# Generated by Django 5.1.3 on 2026-06-22 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "排队中"),
                            ("processing", "处理中"),
                            ("done", "已完成"),
                            ("error", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audio_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "audio_name",
                    models.CharField(default="recording.webm", max_length=255),
                ),
                ("index_type", models.CharField(default="clean", max_length=20)),
                ("result_json", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "匹配任务",
                "verbose_name_plural": "匹配任务",
                "ordering": ["created_at"],
            },
        ),
    ]
