# Generated by Django 4.2.30 on 2026-06-22 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("voice_matching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("celebrity_name", models.CharField(db_index=True, max_length=255)),
                ("nickname", models.CharField(default="", max_length=50)),
                ("score", models.FloatField(db_index=True)),
                (
                    "audio_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("task_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "排行榜条目",
                "verbose_name_plural": "排行榜条目",
                "ordering": ["-score", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["celebrity_name", "-score"],
                        name="voice_match_celebri_0fd971_idx",
                    )
                ],
            },
        ),
    ]
